#ifndef __hial_h
#define __hial_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>

extern Language tree_sitter_rust(void);

extern Language tree_sitter_javascript(void);

#endif /* __hial_h */
