#ifndef __hial_h
#define __hial_h

/* !!! DO NOT MANUALLY MODIFY !!! Autogenerated by cbindgen. */

#include <stdint.h>

extern Language tree_sitter_javascript(void);

extern Language tree_sitter_rust(void);

#endif /* __hial_h */
